# Generated by Django 3.2.7 on 2021-10-07 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='goal',
        ),
        migrations.CreateModel(
            name='PreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=50, verbose_name='目標')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.schedule', verbose_name='予定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
