# Generated by Django 3.2.7 on 2021-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
                ('team_code', models.CharField(max_length=128, verbose_name='team_code')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='team_names',
            field=models.ManyToManyField(blank=True, to='accounts.Team'),
        ),
    ]
