# Generated by Django 3.2.7 on 2021-09-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210913_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'TeamCode',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(blank=True, to='accounts.TeamCode')),
            ],
            options={
                'verbose_name_plural': 'TeamUser',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='team_names',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='teamuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
