# Generated by Django 3.2.7 on 2021-09-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210915_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.AlterField(
            model_name='teamcode',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.team', verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='teams',
            field=models.ManyToManyField(blank=True, to='accounts.Team'),
        ),
    ]
