# Generated by Django 3.2.7 on 2021-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamuser',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='teamuser',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='TeamCode',
        ),
        migrations.DeleteModel(
            name='TeamUser',
        ),
    ]
