# Generated by Django 3.2.7 on 2021-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210924_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_team_admin',
            field=models.BooleanField(default=False, verbose_name='team_admin status'),
        ),
    ]
