# Generated by Django 3.2.7 on 2021-10-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_team_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_team_member',
            field=models.BooleanField(default=False, verbose_name='team_member status'),
        ),
    ]
