# Generated by Django 3.2.7 on 2021-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.CharField(max_length=50, null=True, verbose_name='場所'),
        ),
    ]
